### PR TITLE
Random Name polishing

### PR DESCRIPTION
**Pull request by ArneBab**
Improve the generated names and remove the “do not reload” warning.

Even if people reload 100 times, they still have much much better anonymity
than when they choose a nickname by hand.

The random name generator creates about 1 million unique names,
but they should actually be similar enough to not give away preferences.

(That warning was originally added or proposed by me, and nowadays I
 think that it does more harm than good. We need people to identify
 somewhat with their anonymous ID)

### CODE REVIEW

**Comment by bertm** [comment]
What's the reasoning behind removal of some names? I don't see how the changes are coherent.

`MSC` is gone but the more excotic `CMM` is left in; `rights` is gone while `activists` remains; `G` and `G.` are removed but `E.` is not: what was the idea here?

**Comment by ArneBab** [comment]
The idea is cleaning out the problematic names I saw while skimming the list. There’s more to remove, but it’s better now than it was before.

**Comment by bertm** [comment]
Alright, that sounds reasonable. Your l10n changes look good anyhow.

**Comment by ArneBab** [comment]
thank you for merging!

**Pull request merged**
